/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DynamicLegends: typeof import('./components/legends/DynamicLegends.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconArrowDown: typeof import('@element-plus/icons-vue')['ArrowDown']
    ElIconArrowLeft: typeof import('@element-plus/icons-vue')['ArrowLeft']
    ElIconWarning: typeof import('@element-plus/icons-vue')['Warning']
    ElIconWarningFilled: typeof import('@element-plus/icons-vue')['WarningFilled']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FlatmapVuer: typeof import('./components/FlatmapVuer.vue')['default']
    MultiFlatmapVuer: typeof import('./components/MultiFlatmapVuer.vue')['default']
    SelectionsGroup: typeof import('./components/SelectionsGroup.vue')['default']
    SvgLegends: typeof import('./components/legends/SvgLegends.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
    vPopover: typeof import('element-plus/es')['ElPopoverDirective']
  }
}
